version: "3.8"

services:
  bot:
    build: "."
    depends_on:
      - "db"
    env_file: "./.env"
    links:
      - "db"
    container_name: "yuganda-bot"

  db:
    image: "edgedb/edgedb:nightly"
    env_file: "./.env"
    environment:
      EDGEDB_PASSWORD: "${EDGEDB_PASSWORD}"
      EDGEDB_GENERATE_SELF_SIGNED_CERT: 1
    volumes:
      - ".edgedb:/var/lib/edgedb/data"
    ports:
      - "5656:5656"
      - "8888:8888"
    container_name: "yuganda-db"
